name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 3.0.9
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.2.2 < 3.1.0'

dependencies:
  args: ^2.3.1
  yaml: ^3.1.1
  resource: ^2.1.7
  path: ^1.8.2
  file: ^6.1.2
  archive: ^3.3.0
  platform: ^3.1.0
  process: ^4.2.4
  meta: ^1.8.0
  intl: ">=0.15.0 <1.0.0"
  tool_mobile: ^1.9.5+1
#  tool_mobile:
#    path: ../tool_mobile

dev_dependencies:
  test: ^1.21.1
  test_api: ^0.4.9
  mockito: ^5.2.0
  pedantic: ^1.11.1
  quiver: ^3.1.0
  fake_process_manager: ^0.1.0+1
#    path: ../fake_process_manager
  tool_base_test:
    git: https://github.com/mmcc007/tool_base_test.git
#    path: ../tool_base_test
  collection: any

executables:
  screenshots: main